### ISSUE TITLE
Should support .arcconfig file if found in directory where being run

### ISSUE THREAD

**Issue by MattSeen** [disqus/python-phabricator#11]
When a .arcconfig file is found, I think, the code should pick up the relevant details from it that file as well as trying to get the them from the .arcrc file.

**Comment by EClaesson** [comment]
The corresponding paths on Windows are:
* System config ```%ProgramData%\Phabricator\Arcanist\config``` e.g ```C:\Program Data\Phabricator\Arcanist\config```
* User config ```%AppData%\.arcrc``` e.g: ```C:\Users\MyUsername\AppData\Roaming\.arcrc```
* Project config ```C:\path\to\project\.arcconfig```
* Local project config ```C:\path\to\project\.git\rc\csuppoonrt

**Comment by EClaesson** [comment]
The corresponding paths on Windows are:
* System config ```%ProgramData%\Phabricator\Arcanist\config``` e.g ```C:\Program Data\Phabricator\Arcanist\config```
* User config ```%AppData%\.arcrc``` e.g: ```C:\Users\MyUsername\AppData\Roaming\.arcrc```
* Project config ```C:\path\to\project\.arcconfig```
* Local project config ```C:\path\to\project\.git\arc\config```

**Comment by BYK** [comment]
I think this is done. Please reopen if it doesn't work (or file a new ticket).
