### ISSUE TITLE
Fails with my .arcrc which only contains token

### ISSUE THREAD

**Issue by gnoronha** [disqus/python-phabricator#22]
My .arcrc was produced by running arc install-certificate and looks like this:

```
{
  "hosts": {
    "https:\/\/phabricator[redacted]\/api\/": {
      "token": "cli-[redacted]"
    }
  }
}
```

python-phabricator complains about not finding the user key and, after I added it by hand, it complains about the cert key not being found:

```
>>> phab = Phabricator()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kov/.local/lib/python2.7/site-packages/phabricator-0.4.0-py2.7.egg/phabricator/__init__.py", line 318, in __init__
    self.certificate = certificate if certificate else ARCRC['hosts'][self.host]['cert']
KeyError: 'cert'
>>> 
```

**Comment by koobs** [comment]
Do tests pass after including this commit?

I see this failure:

```
  File "/usr/home/koobs/repos/freebsd/ports/devel/py-phabricator/work/phabricator-0.4.0/phabricator/tests.py", line 14, in setUp
    self.api = phabricator.Phabricator(username='test', certificate='test', host='http://localhost')
  File "/usr/home/koobs/repos/freebsd/ports/devel/py-phabricator/work/phabricator-0.4.0/phabricator/__init__.py", line 296, in __init__
    if token or ARCRC['hosts'][self.host].has_key('token'):
KeyError: 'http://localhost'
```
In the following tests:

test_connect (phabricator.tests.PhabricatorTest) ... ERROR
test_generate_hash (phabricator.tests.PhabricatorTest) ... ERROR
test_maniphest_find (phabricator.tests.PhabricatorTest) ... ERROR
test_user_whoami (phabricator.tests.PhabricatorTest) ... ERROR
test_validation (phabricator.tests.PhabricatorTest) ... ERROR

**Comment by gnoronha** [comment]
Oops, apparently the tests used the installed version so I was misled into thinking they were passing. This new commit fixes that.
