### ISSUE TITLE
Maniphest Info

### ISSUE THREAD

**Issue by pgcrooks** [disqus/python-phabricator#26]
I'm trying to obtain Maniphest task information via the following:

from phabricator import Phabricator
phab = Phabricator()
print phab.user.whoami()
phab.maniphest.info(86)

The whoami call is successful, but the Maniphest call returns the following:

Traceback (most recent call last):
  File ".git/hooks/commit-msg", line 16, in <module>
    phab.maniphest.info(86)
TypeError: __call__() takes exactly 1 argument (2 given)

I might be doing something stupid here, but I can't see what.

Forgot to add:
Python 2.7.9 (default, Mar  1 2015, 12:57:24) 
[GCC 4.9.2] on linux2

**Comment by BYK** [comment]
I think you need to do

    phab.maniphest.info(task_id=86)
