### ISSUE TITLE
Possibly eliminate the Result class?

### ISSUE THREAD

**Issue by avivey** [disqus/python-phabricator#27]
Looks like the `Result` class is a very thin wrapper around the parsed result: All of its methods delegate directly to `self.response`.

Maybe it should be eliminated, and `_request` just return `data['result']`?

**Comment by BYK** [comment]
We have replaced this with a `MutableDict` base. The appeal of having a result class is two-fold if you ask me:

1. Having a specific data type for Phabricator responses that can be subclassed or type-checked when necessary.
2. Easier, "native" attribute access instead of the "cumbersome" `result['key']` pattern.

What do you think?

**Comment by avivey** [comment]
Hi,

First off, I've actually stopped using this package, and replaced it with a home-grown thing, mostly because I do all my api over ssh now (Not recommended; See T550).

Point 1 makes sense in the context of "class-oriented python", which I guess is a good reason to keep it. 

For point 2, are you referring to javascript-like `result.key` syntax? I love that and I often wish python's `dict` would just support it natively... But I found it somewhat confusing that this one dict-like thing supports it.


Anyway, since much of its code has been removed with the switch to `MutableDict`, I guess there's really very little to say in favor of eliminating it.

**Comment by BYK** [comment]
Oh, neat.

>(Not recommended; See T550).

I glanced over T550 and it looks like a good way to do things, especially if you are using Jenkins as you mentioned in that ticket. Why is this not recommended?

I agree with your opinion about point 2 but there's not much to do about it unless you are in the core-python team I guess :) (cc @berkerpeksag)

>Anyway, since much of its code has been removed with the switch to MutableDict, I guess there's really very little to say in favor of eliminating it.

I tend to agree so I'm closing the ticket. Feel free to reopen if you think you find a legitimate case of removing the `Result` class.

Also thanks a lot for your swift and in-depth response!

**Comment by aviv-clover** [comment]
Re T550 - It's just not officially supported, and has some sharp edges, so not really recommended unless you're willing to dig deep and possibly recover from unplanned side-effects :)

**Comment by avivey** [comment]
Re T550 - It's just not officially supported, and has some sharp edges, so not really recommended unless you're willing to dig deep and possibly recover from unplanned side-effects :)

**Comment by BYK** [comment]
Alright. Thanks for the info :)
