### ISSUE TITLE
Fails to initialize Phabricator() on Python 3.4.4

### ISSUE THREAD

**Issue by darander** [disqus/python-phabricator#32]
In python 3, `dict.keys()` returns a dictionary view instead of a list. It might work by calling `list(dict)`, though I haven't tried it. 

    >>> phab = Phabricator()
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/anders/.local/lib/python3.4/site-packages/phabricator/__init__.py", line 330, in __init__
        self.host = host if host else defined_hosts.keys()[0]

**Comment by brabadu** [comment]
It works, but then there's other issues with parsing request responses. I ended up taking source into my script and modifiing it every time it fails

**Comment by BYK** [comment]
PRs welcome. Otherwise I'll try to get to this next week.

**Comment by BYK** [comment]
Fixed with #36.
