### ISSUE TITLE
Unclear copyright holder

### ISSUE THREAD

**Issue by zumbi** [disqus/python-phabricator#34]
Hello,

  I did not find good enough information about copyright holder for this software package, could that be broader clarified?

  For the record, the only copyright match I found was: Copyright 2012 DISQUS
  Could you add a contact email and a clarification of what DISQUS is?

Thanks and best regards

**Comment by BYK** [comment]
Hi @zumbi,

Disqus is the company who created and is maintaining this package. You can find more information at https://disqus.com and https://github.com/disqus

You can use GitHub issues to report issues about the project.
