### ISSUE TITLE
Can we instantiate the phabricator object to a different uri other than .arcrc

### ISSUE THREAD

**Issue by msatish9** [disqus/python-phabricator#35]
Hi,
Is it possible to use the phabricator to connect to a specific conduit uri, I have both the uri's of our phabricator instances in .arcrc but the api is always choosing the default one, it would be great if I could instantiate with the uri address?
phab = phabricator(<uri?)?

Thanks
Satish

**Comment by BYK** [comment]
You can pass the URL you want as the `host` argument: https://github.com/disqus/python-phabricator/blob/master/phabricator/__init__.py#L324

Would that solve your problem?

**Comment by BYK** [comment]
I mean not the URL, the host, as the name suggests.

**Comment by msatish9** [comment]
Yes, that should work! Thanks for the prompt response @BYK , I will give it a try :)

**Comment by BYK** [comment]
No worries! Closing the ticket then. Feel free to reopen or filing a new one if you need more on this.
