### ISSUE TITLE
Certain endpoints do not exist in the interfaces.json, and if added dont work

### ISSUE THREAD

**Issue by flippingtables** [disqus/python-phabricator#38]
Some conduit endpoints are missing. E.g. the Phame related ones.

If I manually add e.g. 
`  "phame.post.edit" : { "description" : "Create a phame post.",
      "params" : { "blog" : "required phid",
          "body" : "required string",
          "title" : "required string"
        },
      "return" : "list<dict>"
},`

to the Interface.json file and try to call it with phab.phame.post.edit, then it fails. As i can see, the final endpoint ends up being `/api/post.edit`, it should be `/api/phame.post.edit`. The library seems to be unable to handle endpoints with multiple `.`.

**Comment by jamesmeador** [comment]
This is addressed in https://github.com/disqus/python-phabricator/pull/40.
