### ISSUE TITLE
Invalid Argument Type

### ISSUE THREAD

**Issue by marcqualie** [disqus/python-phabricator#4]
I am receiving this error when trying to upload files via the Phabricator API. Other calls work fine for both reading and writing, but this one fails.

  File "/Library/Python/2.7/site-packages/phabricator-0.3.0-py2.7.egg/phabricator/__init__.py", line 115, in _request
    raise ValueError('Wrong arguemnt type: %s is not a %s' % (k, resource['required'][k]))
ValueError: Wrong arguemnt type: data_base64 is not a nonempty

Printing out the data to the screen shows that the data is there and it not a None empty type. I can't find any reference in the google or in google searches of nonempty types. Am I overlooking something or is this a bug?

**Comment by BYK** [comment]
I think this was fixed in e822192528c0b69f6d1dfc6ab004a096d438705a.
