### ISSUE TITLE
Result of conduit methods returning only string

### ISSUE THREAD

**Issue by reet-** [disqus/python-phabricator#42]
Hi,

If I call e.g. `file.upload`, which returns _nonempty guid_:

`phid = phab.file.upload(data_base64=content, name=name)`

I get:

`print phid`
`<Result: u'PHID-FILE-xy'>`

But what I want (without parsing the result string) is `PHID-FILE-xy`. Am I missing something?

Thanks!

**Comment by tail** [comment]
You can access it from `phid.response`.

**Comment by reet-** [comment]
@tail Works, thanks!

Closing this issue.
