### ISSUE TITLE
Update pip package

### ISSUE THREAD

**Issue by rraval** [disqus/python-phabricator#47]
Hi there,

19ccedba4c112d3d81799561665f04e5c71a07f8 landed an update to `interfaces.json` that exposes `diffusion.commit.search` without having to do an `update_interfaces()` every time.

Any chance an updated pip package could be released that includes this change? 0.7.0 went out a year ago.

**Comment by schra** [comment]
@thekashifmalik Any chance that we could release a new pip package version? The last version is now already 4 years old ;)

**Comment by thekashifmalik** [comment]
@schra let me take a look tomorrow.

**Comment by thekashifmalik** [comment]
Made a release on [PyPI](https://pypi.org/project/phabricator/).
