### ISSUE TITLE
Mocking resources

### ISSUE THREAD

**Issue by schancel** [disqus/python-phabricator#48]
Any idea how "methods" on this library can be mocked out?  I'm trying to write several tests for another system that uses it, and nothing I do with the mock library seems to be able to replace the `__call__` or `_request` functions on a particular instance of a Resource class.

**Comment by aljungberg** [comment]
Not a direct answer to your question, but I successfully wrote tests using [vcr](http://vcrpy.readthedocs.io/en/latest/usage.html). It captured and replayed the requests made by this library.

(VCR uses a kind of shotgun approach: as far as I can tell it patches urllib, httplib2 and many others.)

**Comment by schancel** [comment]
Ah that's a good point.  Thank you for that.  I'm use to less dynamic languages.
