### ISSUE TITLE
No documentation on how to configure .arcrc file.

### ISSUE THREAD

**Issue by Hypro999** [disqus/python-phabricator#58]
No information whatsoever is given on how to configure the .arcrc file for this library. Ideally, there should be some.

**Comment by Hypro999** [comment]
While I'm here, I might as well point out that the documentation on how to use this library is absolute garbage. You could also call it a sheer disgrace. This is a massive pain for developers who need to use this library because the webhook for Phabricator is also garbage - it forces us to have to use Phabricator's API instead of just explaining what event happened.

**Comment by mattrobenolt** [comment]
Hey @Hypro999, while I understand your frustration, this is completely rude and uncalled for. This library is effectively unmaintained. I’m only responding to this because your comment here was ridiculous. If you feel so strongly about this, you’re free to open a pull requests. 

@timabbott you might wanna talk to your intern here about how to treat open source developers.

**Comment by Hypro999** [comment]
@mattrobenolt, I apologise for the rude comment. I guess that it was indeed uncalled for. I'm really sorry about this.

**Comment by Hypro999** [comment]
Also I wouldn't be able open a pull request since I don't the have information for updating the documentation. The developers would have to do this.

**Comment by Hypro999** [comment]
@mattrobenolt one more thing I think I should clear up here is I did this independently of Tim Abbott or Zulip. This action was **my personal** choice done under **my personal** frustrated judgement.

**Comment by timabbott** [comment]
@mattrobenolt I'm really sorry about this; the comment in question is definitely not in line with Zulip's community standards for our community members interacting with other open source projects.

**Comment by rht** [comment]
Passerby here.

> This library is effectively unmaintained.

While this can be inferred from the commit timestamps (even then, the last commit was as recent as a year ago), I still think it would be informative to other devs if the readme warns so with a disclaimer.

**Comment by YuZongYangHi** [comment]
hi everybody, The configuration file will be generated by default when you execute the token：

`
git clone git@gitlab.hobot.cc:HoPublic/libphutil.git

git clone git@gitlab.hobot.cc:HoPublic/arcanist.git

arc set-config default https://cr.hobot.cc/

arc install-certificate
`
